# Generated by Django 5.2.3 on 2025-06-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundraise", "0002_rename_item_donors"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="donors",
            options={"managed": False},
        ),
    ]
