# Generated by Django 5.2.3 on 2025-06-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("fundraise", "0003_alter_donors_options"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="donors",
            table="donors",
        ),
    ]
