# Generated by Django 5.2.3 on 2025-06-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraise", "0004_alter_donors_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="TotalAmountPerCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("campaign_id", models.IntegerField(blank=True, null=True)),
                (
                    "total_amount_per_campaign",
                    models.IntegerField(blank=True, null=True),
                ),
            ],
            options={
                "db_table": "total_amount_per_campaign",
                "managed": False,
            },
        ),
    ]
