# Generated by Django 5.2.3 on 2025-06-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraise", "0005_totalamountpercampaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaigns",
            fields=[
                ("campaign_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "total_amount_per_campaign",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "usd",
                    models.CharField(
                        blank=True, db_column="USD", max_length=10, null=True
                    ),
                ),
                (
                    "zar",
                    models.CharField(
                        blank=True, db_column="ZAR", max_length=10, null=True
                    ),
                ),
                (
                    "eur",
                    models.CharField(
                        blank=True, db_column="EUR", max_length=10, null=True
                    ),
                ),
                (
                    "total_donors_per_campaign_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("completed", models.CharField(blank=True, max_length=10, null=True)),
                ("failed", models.CharField(blank=True, max_length=10, null=True)),
                ("pending", models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                "db_table": "campaigns",
                "managed": False,
            },
        ),
        migrations.DeleteModel(
            name="TotalAmountPerCampaign",
        ),
    ]
