# Generated by Django 5.2.3 on 2025-06-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fundraise", "0006_campaigns_delete_totalamountpercampaign"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationData",
            fields=[
                ("donation_id", models.IntegerField(primary_key=True, serialize=False)),
                ("donor_id", models.IntegerField(blank=True, null=True)),
                ("amount", models.FloatField(blank=True, null=True)),
                ("currency", models.TextField(blank=True, null=True)),
                ("donation_date", models.TextField(blank=True, null=True)),
                ("campaign_id", models.IntegerField(blank=True, null=True)),
                ("status", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "donation_data",
                "managed": False,
            },
        ),
    ]
